// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ojATU-W8ySy495MdnvfA-YnMUq5MIuo',
    appId: '1:1096596643983:web:7d9a3bafb7b5a11b5c50fa',
    messagingSenderId: '1096596643983',
    projectId: 'cirkle-57cc6',
    authDomain: 'cirkle-57cc6.firebaseapp.com',
    storageBucket: 'cirkle-57cc6.firebasestorage.app',
    measurementId: 'G-3XCRV0W6M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtLNbQ68ZmFbPY3SdPSeVvMS4TfZf2gI8',
    appId: '1:1096596643983:android:4e01a9910806f4665c50fa',
    messagingSenderId: '1096596643983',
    projectId: 'cirkle-57cc6',
    storageBucket: 'cirkle-57cc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGz5hHcwZ_JuhAGjoGqU_MSaIAlK-NHTQ',
    appId: '1:1096596643983:ios:bb4ddd14f7a56a7a5c50fa',
    messagingSenderId: '1096596643983',
    projectId: 'cirkle-57cc6',
    storageBucket: 'cirkle-57cc6.firebasestorage.app',
    iosBundleId: 'com.example.cirmleRfidPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGz5hHcwZ_JuhAGjoGqU_MSaIAlK-NHTQ',
    appId: '1:1096596643983:ios:bb4ddd14f7a56a7a5c50fa',
    messagingSenderId: '1096596643983',
    projectId: 'cirkle-57cc6',
    storageBucket: 'cirkle-57cc6.firebasestorage.app',
    iosBundleId: 'com.example.cirmleRfidPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7ojATU-W8ySy495MdnvfA-YnMUq5MIuo',
    appId: '1:1096596643983:web:04dcc0e6be0afa7f5c50fa',
    messagingSenderId: '1096596643983',
    projectId: 'cirkle-57cc6',
    authDomain: 'cirkle-57cc6.firebaseapp.com',
    storageBucket: 'cirkle-57cc6.firebasestorage.app',
    measurementId: 'G-ZCTE773HH3',
  );
}
